Update file .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -49,6 +49,9 @@ create-release:
   rules:
     - if: $CI_COMMIT_TAG
   script: |
+    echo "Checking for zip file:"
+    ls -lh "$ZIP_NAME" || echo "Zip not found"
+    
     echo "Installing curl and jq..."
     apk add --no-cache curl jq
 
