Update file .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -68,12 +68,20 @@ create-release:
      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/uploads" > upload_response.json
     
     cat upload_response.json
-    RELATIVE_URL=$(jq -r '.direct_asset_url' upload_response.json)
-    ABSOLUTE_URL="${GITLAB_DOMAIN}${RELATIVE_URL}"
+    UPLOAD_URL=$(jq -r '.url // .direct_asset_url' upload_response.json)
 
-    echo "Adding asset link to release - $ABSOLUTE_URL"
+    # Make sure $UPLOAD_URL is not null or empty
+    if [ -z "$UPLOAD_URL" ] || [ "$UPLOAD_URL" = "null" ]; then
+      echo "Upload URL is empty or null, aborting."
+      exit 1
+    fi
+
+    FULL_URL="${GITLAB_DOMAIN}${UPLOAD_URL}"
+
+    echo "Adding asset link to release - $FULL_URL"
+
     curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
       --request POST \
       --header "Content-Type: application/json" \
-      --data "{\"name\":\"$ZIP_NAME\",\"url\":\"$ABSOLUTE_URL\",\"link_type\":\"other\"}" \
+      --data "{\"name\":\"$ZIP_NAME\",\"url\":\"$FULL_URL\",\"link_type\":\"other\"}" \
       "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
