Update file .gitlab-ci.yml

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -5,7 +5,7 @@ stages:
 variables:
   BINARY_NAME: "beszel-agent_windows_amd64.exe"
   GITLAB_DOMAIN: "https://gitlab.prplanit.com"
-  OUTPUT_DIR: "agent_windows_amd64-$CI_COMMIT_TAG"
+  OUTPUT_DIR: "beszel-agent_windows_amd64-$CI_COMMIT_TAG"
   ZIP_NAME: "$OUTPUT_DIR.zip"
 
 build-release:
@@ -49,6 +49,32 @@ create-release:
   rules:
     - if: $CI_COMMIT_TAG
   script: |
+    echo "Checking for zip file:"
+    ls -lh "$ZIP_NAME" || echo "Zip not found"
+
+    echo "Installing curl and jq..."
+    apk add --no-cache curl jq
+
+    echo "Creating release $CI_COMMIT_TAG"
+    curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" --request POST \
+      --form "name=Release $CI_COMMIT_TAG" \
+      --form "tag_name=$CI_COMMIT_TAG" \
+      --form "description=Automated release for $CI_COMMIT_TAG" \
+      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases"
+
+    echo "Publishing ZIP to Generic Package Registry..."
+    curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
+      --upload-file "$ZIP_NAME" \
+      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/packages/generic/beszel-agent/${CI_COMMIT_TAG}/${ZIP_NAME}"
+
+    PACKAGE_URL="${GITLAB_DOMAIN}/${CI_PROJECT_PATH}/-/packages"
+
+    echo "Adding asset link to release - $PACKAGE_URL"
+    curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN" \
+      --request POST \
+      --header "Content-Type: application/json" \
+      --data "{\"name\":\"$ZIP_NAME\",\"url\":\"$PACKAGE_URL\",\"link_type\":\"package\"}" \
+      "$CI_API_V4_URL/projects/$CI_PROJECT_ID/releases/$CI_COMMIT_TAG/assets/links"
     echo "Checking for zip file:"
     ls -lh "$ZIP_NAME" || echo "Zip not found"
 
